#!/bin/bash
d=""; [ "$1" = -d ] && { d=-d; shift; }
if [ $# -eq 0 ]; then exec /usr/bin/mktemp $d "/private/tmp/wsbox/w-20261005-191428-dd05/scratchpad/t/tmp.XXXXXXXX"; fi
exec /usr/bin/mktemp $d "$@"
