#!/usr/bin/env python3
# HISTORY ONLY. This produced FACTORY-SPEC-v2.md from v1 on the machine that wrote the drafts; its paths do not resolve here.
"""Produces FACTORY-SPEC-v2.md from FACTORY-SPEC.md (v1) by surgical section replacement. v1 is left untouched."""
import re
from pathlib import Path

ROOT = Path("/home/claude/research")
v1 = (ROOT / "FACTORY-SPEC.md").read_text()

# split into preamble + H2 sections
parts = re.split(r"(?m)^(?=## )", v1)
pre, sections = parts[0], parts[1:]
sec = {}
order = []
for s in sections:
    key = s.splitlines()[0][3:].strip()
    sec[key] = s
    order.append(key)

def k(prefix):  # find key by numeric prefix
    return next(x for x in order if x.startswith(prefix))

def replace_in(key, old, new, count=1):
    assert old in sec[key], (key, old[:60])
    sec[key] = sec[key].replace(old, new, count)

# ---- global rename factory -> factory918 in CLI/file names (not in prose "the factory") ----
def rename(s):
    s = s.replace("`factory.sh`", "`factory918.sh`").replace("factory.sh", "factory918.sh")
    for cmd in ["init", "apply", "doctor", "update", "sync", "labels", "sync-repos"]:
        s = s.replace(f"`factory {cmd}", f"`factory918 {cmd}").replace(f"factory {cmd}", f"factory918 {cmd}")
    s = s.replace("(working name `factory`)", "(`factory918`)").replace("`factory` is a placeholder", "the name is Factory918")
    return s
for key in order:
    sec[key] = rename(sec[key])

# ---- changelog + title ----
pre = pre.replace("# The Factory", "# The Factory, v2 (Factory918)", 1)
pre = pre.replace("First draft, 2026-09-09.", "Second draft, 2026-09-09; v1 is preserved as `FACTORY-SPEC.md`.", 1)
changelog = """
## Change log, v1 → v2

Surgical edits only; unchanged sections are verbatim from v1.

- **§0**: the implementing model loads the writing skills before writing anything for other models; the knowledge base is its reference; it never reads a knowledge file whole.
- **§1**: Manuel's settled decisions added (comments stay, thin hook, never block on the human, auto-PR from tickets, private monorepos, Expo/RN, Python profile, model policy, name).
- **§3**: the roof (`/factory918`), the Day-0 interview (`/factory-start`) and the knowledge base are part of the loop, not afterthoughts.
- **§4**: layout adds `docs/knowledge/` (full corpus, generated by `build_knowledge.py`), `profiles/` (vite-plus, react-native, python), `ast-grep/`, the three glue skills, `docs/factory918/` slim copies in projects, `docs/agents/models.md` and `ledger.md`; removes `no-comments` and the Comment Sicko agent.
- **§5**: manifest and patch list updated accordingly; `unslop` stays auto-firing; `no-comments` excluded.
- **§6**: the comments contradiction is resolved in Manuel's favour.
- **§7**: new 7.10 Profiles (React Native, Python), 7.11 Cross-language rules (`ast-grep`), 7.12 Models and cost; 7.6 and 7.7 updated for the voice and the comments policy.
- **§8**: CLI is `factory918`; `apply --profile`; `doctor` checks the glue; `knowledge` regeneration.
- **§9**: milestones reordered so the writing skills and the knowledge base come before any template prose.
- **§10**: decisions moved to `DECISIONS.md`; only deferred items remain.
- **§11**: glossary additions for the new tools.
"""
pre = pre.rstrip() + "\n" + changelog + "\n---\n\n"

# ---- §0 ----
key0 = k("0.")
replace_in(key0, "5. **Ask Manuel only for [decide] items.** Everything else has a default in this document.",
"""5. **Ask Manuel only for [decide] items.** Everything else has a default in this document or in `docs/knowledge/core/DECISIONS.md`, which wins over this document where they differ.
6. **Load the writing skills into your own session before you write anything another model will read.** Install `writing-for-agents` (Matt), `technical-writing` and `unslop` (pstack) from the bundle into `~/.claude/skills/` for the duration of the build; apply `writing-for-agents` to every skill, playbook, mandate and `AGENTS.md` text, and `technical-writing` + `unslop` to every human-facing document. `deslop` applies to code you write (`factory918.sh`, hooks, the lint plugin).
7. **The knowledge base is your reference; read it by section.** `docs/knowledge/INDEX.md` lists every file with its line count and when to read it; `core/PHILOSOPHY.md` is the one file to read whole. Use the `knowledge` skill's procedure (grep, mini-TOC, ranged Read) for everything else. Never read a knowledge file over 200 lines without `offset`/`limit`.""")
replace_in(key0, "`factory-skeleton/` in the same bundle contains drafts", "`factory918-skeleton/` in the same bundle contains drafts")

# ---- §1 ----
key1 = k("1.")
sec[key1] = sec[key1].rstrip() + """

**Settled decisions (2026-09-09; full table with reasons in `docs/knowledge/core/DECISIONS.md`).** Comments stay in the code; pstack's `/no-comments` is not run. The commit hook is thin (formatter only). Never block on the human, except irreversible actions. A ticket auto-opens a PR that closes it; the human merges. Repositories are private; one monorepo per product by default. Mobile is Expo / React Native, not Flutter. Python is supported as a profile (`uv`, `ruff`, `pyright`, `pytest`). Cross-language custom rules use `ast-grep`. Opus 5 is the default model, Sonnet 5 for mechanical delegates, Fable 5.1 reserved for judgment that is the product. The knowledge base lives in the Factory918 repo with slim copies in projects. The name is Factory918.

"""

# ---- §3 ----
key3 = k("3.")
replace_in(key3, "Where the human is:",
"""Three pieces of glue make this a system rather than parts: **`/factory918`**, a router above Matt's and pstack's routers that maps any situation to its entry point; **`/factory-start`**, the Day-0 interview that asks only the decisions the template cannot make and writes them into the project, so "ready to plan the moment the loader finishes" is literally true; and **`docs/knowledge/`** with the **`/knowledge`** skill, the philosophy, manual, decisions and sources an agent with no memory can consult by section. The session mandate names the roof; `AGENTS.md` points at all three.

Where the human is:""")

# ---- §4 (replace whole) ----
key4 = k("4.")
sec[key4] = """## 4. Repository layout of the factory

```
factory918/                           the template repo (its own git repo, MIT)
├── README.md
├── SOURCES.md                        upstream repos, shas, paths taken, exclusions, patches applied (feeds `factory918 sync`)
├── VERSION
├── factory918.sh                     the CLI: init | apply [--profile] | doctor | update | sync | sync-repos | labels | knowledge
├── manifest.schema.json              what .factory918/manifest.json in a project looks like
├── build_knowledge.py                regenerates docs/knowledge/ from sources
├── patches/                          patch files applied to vendored skills (§5.4)
├── docs/knowledge/                   THE FULL CORPUS (not copied into projects; `/knowledge` reads it from here)
│   ├── INDEX.md                      every file, its line count, when to read it
│   ├── core/  PHILOSOPHY.md  MANUAL.md  DECISIONS.md  GLOSSARY.md  CONVERSATION-DIGEST.md
│   ├── spec/  FACTORY-SPEC-v2 (chunked)  FACTORY-SPEC-v1 (chunked)
│   ├── pages/ four-skill-systems/  deterministic-layer/  pocock-planning-evidence/   (chunked by section)
│   └── notes/ 1-matt-pocock/ 2-theo/ 3-pstack/ 4-ras-mic/ 6-deterministic-layer/       (chunked by section)
├── profiles/
│   ├── vite-plus/README.md           the default; points at the template files
│   ├── react-native/  README.md  mobile-fingerprint-check.yml (T3 Code, MIT)  eas.json.example
│   └── python/        README.md  pyproject.toml  python.yml  .pre-commit-config.yaml
└── template/                         everything below is copied into a project
    ├── AGENTS.md                     the letter (§7.6); CLAUDE.md is the line `@AGENTS.md`
    ├── CLAUDE.md
    ├── CONTEXT.md                    empty glossary skeleton in Matt's format
    ├── CODING_STANDARDS.md           read at review time (§7.7)
    ├── docs/factory918/              slim copies: PHILOSOPHY.md  MANUAL.md  DECISIONS.md  GLOSSARY.md
    ├── .agents/skills/               vendored + custom skills (one folder, every harness)
    │   ├── pstack (51 dirs: all of open-pstack's except no-comments)                     ← from open-pstack
    │   ├── grilling/ grill-me/ grill-with-docs/ domain-modeling/ to-spec/ to-tickets/ wayfinder/
    │   │   research/ prototype/ setup-matt-pocock-skills/ writing-for-agents/ wizard/ wait-what/
    │   │   spec-review/ (renamed from code-review)                                       ← from mattpocock/skills
    │   └── factory918/ factory-start/ knowledge/ mode-plan/ mode-build/ factory-doctor/  ← ours
    │       (+ poteto-mode/playbooks/ticket.md, ours, inside the vendored router)
    ├── .claude/
    │   ├── skills -> ../.agents/skills   (symlink; T3 Code's pattern)
    │   ├── agents/                    pstack-fable-*.md, pstack-opus-*.md, poteto-agent.md  (no comment-sicko)
    │   ├── settings.json              hooks (§7.4)
    │   └── hooks/  mode.sh  format-on-write.sh  block-dangerous-git.sh  session-start.sh  session-mandate.md
    ├── docs/agents/
    │   ├── issue-tracker.md  domain.md  triage-labels.md      Matt's GitHub templates, pre-filled
    │   ├── review-ladder.md  evidence.md  feedback-loops.md   §7.5
    │   ├── models.md                  the role→model defaults for /setup-pstack (§7.12)
    │   └── ledger.md                  one line per surprise; rules are promoted from here
    ├── docs/adr/0001-toolchain.md
    ├── vite.config.ts                 fmt / lint / staged / test (§7.2)
    ├── oxlint-plugin-project/         index.ts + rules/ + one starter rule with test (§7.3)
    ├── ast-grep/                      sgconfig.yml + rules/ + rule-tests/ (§7.11)
    ├── .vite-hooks/pre-commit         `vp staged`
    ├── .github/
    │   ├── workflows/ci.yml  pr-size.yml  labels.yml
    │   ├── labels.json  pull_request_template.md  pr-assets/.gitkeep
    ├── .repos/README.md  sources.json  vendored reference sources go here, read-only (§7.9)
    ├── tsconfig.base.json  .editorconfig  .gitignore.factory  package.scripts.json
```

Why one skills folder: Claude Code reads `.claude/skills/`; Codex, T3 Code and Ras Mic's set read `.agents/skills/`; T3 Code keeps the two byte-identical through a symlink **[primary]**. Why the knowledge base stays in the factory repo: projects carry the four core documents and the `knowledge` skill, which reads the full corpus from `$FACTORY918_HOME` (default `~/.factory918`, the clone the CLI runs from). One place to update, light projects.

"""

# ---- §5.1: exclusions + models ----
key5 = k("5.")
replace_in(key5, "Take `plugins/pstack/skills/*` (all except `make-bot-ui`), `plugins/pstack/agents/*`, and the hook text `plugins/pstack/hooks/session-start-context.md`.",
"Take `plugins/pstack/skills/*` except `make-bot-ui` (not in the port) and `no-comments` (excluded by decision 4: comments stay); `plugins/pstack/agents/*` except `comment-sicko.md`; and the hook text `plugins/pstack/hooks/session-start-context.md` as raw material for our own mandate (§7.4).")
replace_in(key5, "Default for a Claude-only user: every non-Claude role → `inherit-parent`; panels collapse to Claude tiers. **[decide]** the tiers (a reasonable default mirrors pstack-claude's `models.json`: single-role default Opus 5, judgment on Fable, panels Opus / Fable / Sonnet).",
"The defaults for Manuel's plan are in `template/docs/agents/models.md` (§7.12): Opus 5 default, Sonnet 5 for mechanical delegates and explorers, Fable 5.1 reserved, `arena` off. Decided (DECISIONS.md #13).")
# 5.3 ours
replace_in(key5, "`ticket` (a playbook file inside `poteto-mode/playbooks/` plus one routing line in the router), `mode-plan` / `mode-build` (two-line user-invoked skills that write `.claude/state/mode`), `factory-doctor` (runs the checks in §8 M1 and reports), and the evidence conventions file.",
"""`factory918` (the roof: a situation → entry-point table; model-invocable with a narrow description so an unsure agent can consult it), `factory-start` (the Day-0 interview: calls Matt's `grilling` over the eight decisions the template cannot make, then writes the `AGENTS.md` slots, ADR 0001, `.repos/sources.json`, the review-ladder bot list and `ledger.md`; user-invoked), `knowledge` (the lookup procedure over `docs/knowledge/`: index, grep, mini-TOC, ranged Read, cite; model-invocable), `ticket` (a playbook file inside `poteto-mode/playbooks/` plus one routing line in the router), `mode-plan` / `mode-build` (two-line user-invoked skills that write `.claude/state/mode`), `factory-doctor` (runs the checks in §8.3 and reports), and the evidence conventions file. Drafts of all three glue skills are in `factory918-skeleton/template/.agents/skills/`.""")
# 5.4 patch 3 rewrite
replace_in(key5, """3. **Opening a PR → review ladder.** In `playbooks/opening-a-pr.md`, after the `/no-comments` line, insert: "Run `spec-review` in a fresh context against the originating ticket and the repo's `CODING_STANDARDS.md`; address Act-on items; record the rest in the PR body. See `docs/agents/review-ladder.md`." Keep "never as a draft.\"""",
"""3. **Opening a PR → comments stay, review ladder added.** In `playbooks/opening-a-pr.md`, replace the sentence "Run `/no-comments` before review." with "Keep comments (DECISIONS.md #4); do not run `/no-comments`. After CI is green, run `spec-review` in a fresh context against the originating ticket (and its parent spec) and `CODING_STANDARDS.md`; fix Act-on items, record the rest in the PR body. The full ladder is `docs/agents/review-ladder.md`." Also replace the later "A subagent that opens a PR runs `interrogate`, `/deslop`, and `/no-comments`" with "... runs `interrogate` and `/deslop`". Keep "never as a draft.\"""")
replace_in(key5, "5. **`unslop` trigger.**", "5. **`unslop` trigger (kept).**")
sec[key5] = sec[key5].rstrip() + """

9. **Session mandate.** Ours replaces the port's: it names the roof (`factory918`), the phases, the direct entries, and the precedence of `AGENTS.md` and `DECISIONS.md`. Draft in `template/.claude/hooks/session-mandate.md`.
10. **Paths in our own files.** In `AGENTS.md`, the mandate and the glue skills, `PHILOSOPHY.md` / `MANUAL.md` / `DECISIONS.md` / `GLOSSARY.md` resolve to `docs/factory918/` inside a project and to `docs/knowledge/core/` inside the factory repo. The `knowledge` skill's `$KB` fallback order is `$FACTORY918_HOME/docs/knowledge`, `~/.factory918/docs/knowledge`, then the project's `docs/factory918`.

"""

# ---- §6 comments row ----
key6 = k("6.")
replace_in(key6, "| Comments are a smell and get deleted (pstack) vs \"Comments describe how a thing is used\" (Theo) | no-comments, comment-sicko vs AGENTS.md Taste | Keep pstack's default in Opening a PR. **[decide]** to remove that line while you are learning; the smell rules still apply. | opening-a-pr.md |",
"| Comments are a smell and get deleted (pstack) vs \"Comments describe how a thing is used\" (Theo) | no-comments, comment-sicko vs AGENTS.md Taste | **Resolved by Manuel: comments stay.** `no-comments` and the Comment Sicko agent are not vendored; Opening a PR no longer runs it; `AGENTS.md` Taste says so in his words. The other Fowler smells still apply at review. | DECISIONS.md #4; opening-a-pr.md patch; AGENTS.md |")

# ---- §7 edits + new subsections ----
key7 = k("7.")
replace_in(key7, "3. **A note from Manuel** — taste, in first person, Theo's structure:", "3. **A note from Manuel** — in his own words (decision 16), assembled from his sentences: stability with minimal weight, one codebase per platform, copy professional patterns until you have your own, never block on the human except the irreversible, comments stay. Theo's structure, Manuel's voice. Draft in `template/AGENTS.md`. Previously:")
replace_in(key7, "12. **Taste** — Theo's five lines, and a pointer: \"Standards used at review time are in `CODING_STANDARDS.md`.\"",
"12. **Taste** — Theo's lines with the comment line rewritten (\"Comments stay... Do not delete comments to make a diff look cleaner\"), and a pointer: \"Standards used at review time are in `CODING_STANDARDS.md`.\"")
replace_in(key7, "1. **One paragraph:** what this project is, its surfaces, who uses it. (slot)",
"1. **One paragraph:** what this project is, its surfaces, who uses it (slot, written by `/factory-start`), followed by the roof pointer: \"This repo runs Factory918. If you are unsure what to do, invoke the `factory918` skill\" and pointers to `PHILOSOPHY.md`, `MANUAL.md`, `DECISIONS.md`, `knowledge`.")
replace_in(key7, "8. **Verifying** — the exact commands (`vp check`, `vp test run <files>`, `pnpm typecheck`);",
"8. **Verifying** — the exact commands per profile (`vp check`, `vp test run <files>`, `pnpm typecheck`; mobile adds `expo`/EAS; Python adds `uv run ruff format --check`, `uv run ruff check`, `uv run pyright`, `uv run pytest`);")
replace_in(key7, "Theo's taste (complexity at the adapter boundary, orchestration pure, UI dumb; inferred types over annotations; comments describe use and move with the code);",
"Theo's taste (complexity at the adapter boundary, orchestration pure, UI dumb; inferred types over annotations); comments stay and describe use and non-obvious why, and move with the code (decision 4);")
sec[key7] = sec[key7].rstrip() + """

### 7.10 Profiles (React Native, Python)

The deterministic layer is a shape; a profile is the set of commands and files that realise it for one language. Three ship; the CLI applies them with `factory918 apply --profile <name>`, and `/factory-start` tells you which ones a repo needs.

**`vite-plus` (default).** Every TypeScript surface. The files in §7.2–7.4 and §7.8. Monorepo shape: `apps/web`, `apps/admin`, `apps/mobile`, `packages/shared`, `scripts/`, `python/<name>`.

**`react-native` (Expo).** Applies on top of `vite-plus`. Exemplar: T3 Code Mobile, which runs Expo SDK 57 and React Native 0.86 with `"test": "vp test run"` (139 Vitest files), `"typecheck": "tsc --noEmit"`, the root oxlint config, and EAS build profiles `development` / `preview` / `production` **[primary: t3code apps/mobile/package.json, eas.json]**. So format, lint, types, unit tests, the commit hook, CI Check and Test, size labels, the PR contract, the review ladder and the evidence conventions all carry over unchanged; the mobile app is one more workspace package. The profile adds: an Expo managed app under `apps/mobile/` (no committed `ios/` or `android/`), `eas.json`, T3 Code's `mobile-fingerprint-check.yml` verbatim (MIT; advisory; labels a PR `📱 Native Change` when the native fingerprint moves, so native PRs are batched before a store build; edit its `paths`), the generated `verify-<app>-mobile` skill with `test-t3-mobile` as the exemplar (simulator launched by the primary agent only; screenshots via `xcrun simctl io booted screenshot` or `adb exec-out screencap -p` are the evidence), optional Maestro flows for e2e, and `packages/shared` for code both surfaces use. Theo's native-lint gate (a Linux job that detects `.swift`/`.kt` changes and fails open, gating a macOS SwiftLint/ktlint/detekt job) is documented and applied only if the app ejects or adds native modules. Full text: `profiles/react-native/README.md`.

**`python`.** Rung for rung: `Enum`/`Literal`/`NewType`/frozen dataclasses and pydantic at boundaries for unrepresentable state; `ruff check` with a curated `select` plus `[tool.ruff.lint.flake8-tidy-imports.banned-api]` for banned APIs with messages (the "encoded opinion" rung) and `per-file-ignores` plus a ratchet test as the debt ceiling; `ruff format`; `pyright` strict (Astral's `ty` is the likely swap once stable); `pytest`; `uv audit` for dependencies; in a monorepo the same commit hook formats `*.py` (`staged: { "*.py": "uv run ruff format" }`, multi-glob support to be verified at M0), standalone repos use `pre-commit` with the official ruff format hook; a `python.yml` CI job (`uv sync --frozen`, format check, `ruff check`, `pyright`, `pytest`, `uv audit`) that runs only when `python/**` changes. Astral joined OpenAI's Codex team in March 2026; the tools remain open source and shipping **[secondary: astral.sh/blog]**. Full text with the `pyproject.toml`, workflow and pre-commit drafts: `profiles/python/README.md`.

**Flutter** is not a profile. Decision 10 chose Expo/RN; a Flutter profile would be a second language and layer with no exemplar among the four sources. If a project ever demands it, the shape carries (`dart format`, `flutter analyze` with `custom_lint`, `flutter test`, Patrol or Maestro for e2e, the official Dart and Flutter MCP server for agent-driven verification) and the profile can be added without touching anything else.

### 7.11 Cross-language custom rules (`ast-grep`)

Theo's encoded opinions live in an oxlint plugin and therefore only reach TypeScript. For opinions that should hold in every language (no `console.log`/`print` in shipped code, banned patterns, structural rules), the factory uses `ast-grep`: YAML rules (`id`, `language`, `severity`, `message`, `rule.pattern`) under `ast-grep/rules/`, tests under `ast-grep/rule-tests/` run with `ast-grep test`, and `ast-grep scan` in the CI Check job. Two starter rules ship (`no-console-log-ts`, `no-print-py`) as the demonstration that one opinion becomes two one-file rules. Debt ceilings for ast-grep rules are a counting script, not a rule option. Verify the config keys, the `scan` exit code and the test harness at M0 **[draft]**.

### 7.12 Models and cost

Manuel is on the $200 Claude plan with access to Fable 5.1, Opus 5 and Sonnet 5; the limit is shared and Fable spends it fastest (one research conversation cost a tenth of a week). The role table `/setup-pstack` writes is therefore where cost control lives, and it is one file. Defaults (`template/docs/agents/models.md`): Opus 5 for the interactive session and for bug-fix/perf roles; Sonnet 5 for feature and refactoring delegates, explorers, investigators and swarm workers; Opus 5 for judgment and prose with Fable on request per ticket; panels Opus + Sonnet, Fable added only for `interrogate` on a contested design; `arena` off. In planning: grill on Opus, switch to Fable with `/model` for `/to-spec` and `/to-tickets`, switch back. The manual lists the skills in cost order (arena, swarm, interrogate, `how` critique mode, wayfinder's parallel research, `to-tickets` on a large spec) and the weekly check (if Fable is over a third of spend, move a role down).

"""

# ---- §8 ----
key8 = k("8.")
replace_in(key8, "- `factory918 apply [<dir>]` — copies `template/` into the project,",
"- `factory918 apply [<dir>] [--profile react-native|python]` — copies `template/` into the project (and, with `--profile`, the profile's files: workflow, `eas.json.example` or `pyproject.toml`, `python.yml`, `.pre-commit-config.yaml`), records applied profiles in the manifest,")
replace_in(key8, "- `factory918 labels` — the `gh label create --force` loop from `.github/labels.json`.",
"- `factory918 labels` — the `gh label create --force` loop from `.github/labels.json`.\n- `factory918 knowledge` — runs `build_knowledge.py` to regenerate `docs/knowledge/` in the factory repo after any source or spec change; `factory918 update` copies the four slim core files into projects.\n- `factory918 sync-repos` — shallow-clones `.repos/sources.json` entries read-only.")
replace_in(key8, "`~/.claude/pstack-models.md` exists.",
"`~/.claude/pstack-models.md` exists; `AGENTS.md` contains no `<slot>` markers (i.e. `/factory-start` has run); `docs/factory918/PHILOSOPHY.md` and `MANUAL.md` are present; the `factory918`, `factory-start` and `knowledge` skills resolve; `docs/agents/ledger.md` exists; every applied profile's files are present (`eas.json`, `pyproject.toml`) and, for the python profile, `uv --version` succeeds.")

# ---- §9 replace ----
key9 = k("9.")
sec[key9] = """## 9. Milestones for the implementing model

Each milestone ends with its acceptance checks run and their output pasted into the PR that lands it (the factory repo uses its own PR contract from day one). The order matters: nothing is written for another model before the writing skills are loaded, and no template prose is written before the philosophy and manual exist to write it against.

**M0 — Ground truth and tools (½ day).** Read `docs/knowledge/core/PHILOSOPHY.md` whole and `MANUAL.md` whole; read this spec whole; read `INDEX.md`. Install `writing-for-agents`, `technical-writing`, `unslop` and `deslop` into your own session (§0 rule 6). Record tool versions (`vp`, `vite-plus`, `@oxlint/plugins`, `ast-grep`, `uv`, `ruff`, `pyright`, `claude`). Confirm: `vp create --no-interactive` flags, `vp hooks enable`/`status`, multi-glob `staged`, `setup-vp@v1` inputs, `@oxlint/plugins` exports, `ast-grep` config keys and `scan`/`test` behaviour, `setup-uv` inputs, the ruff `select` codes against the installed version, Claude Code hook events used, and `disable-model-invocation` semantics. Acceptance: `M0-findings.md` with one line per fact and its source URL; every deviation from this spec listed with the fix you intend.

**M1 — Vendor the skills (½ day).** §5.1–5.2 and the patch list §5.4 as `patches/` plus `SOURCES.md` with exclusions. Acceptance: 69 skill directories minus `no-comments` (68) with no duplicate `name:`; no `pstack:` namespace residue; Matt's planning entry points still carry `disable-model-invocation: true`; every pstack action skill does not; `spec-review` renamed; the Ticket playbook and router line present; `opening-a-pr.md` no longer mentions `/no-comments`.

**M2 — The truth (1 day).** `docs/knowledge/` from `build_knowledge.py` (all core documents, both specs, the three pages, the notes; chunked; `INDEX.md`); the three glue skills (`factory918`, `factory-start`, `knowledge`) written against `writing-for-agents`; the session mandate. Acceptance: `INDEX.md` lists every file with a line count; no chunk exceeds 240 lines; each chunk's mini-TOC line numbers resolve to the headings they name (spot-check five with `sed -n`); in Claude Code inside the factory repo, `/knowledge why do comments stay` answers with a `DECISIONS.md:line` citation and reads fewer than 200 lines in total (check the transcript); `/factory918` returns an entry point for each row of its table when prompted with that situation.

**M3 — Template files (1 day).** §4 and §7, with `AGENTS.md` written last because it points at everything else, in Manuel's voice, passed through `writing-for-agents`; `docs/factory918/` slim copies; `docs/agents/models.md` and `ledger.md`; profiles' files under `profiles/`. Acceptance: on a fresh `vp create vite:monorepo --no-interactive` project, `factory918 apply` then `factory918 doctor` fails only on the "slots filled" and label checks; a deliberately unformatted file lands formatted after `git commit`; a `// TODO later` comment fails `vp lint`; `console.log` fails `ast-grep scan`; a stale `// oxlint-disable` fails `vp lint`; CI on a throwaway repo goes green, then red when a test is broken on purpose.

**M4 — Hooks and the Day-0 flow (½ day).** §7.4 and `/factory-start`. Acceptance: `/factory-start` on the M3 project asks only the eight decisions, writes every slot, creates `ledger.md`, and `factory918 doctor` then passes every check; typing `/grill-with-docs` sets the phase to planning and the next prompt's context shows the planning line; `/mode-build` flips it; a file written by the agent is formatted before the next tool call; `git push origin main` and `git reset --hard` are refused with a visible BLOCKED message; `git push origin feat/x` is allowed; the mandate appears after `/clear` and names `factory918`.

**M5 — GitHub layer (½ day).** §7.8 plus the branch-protection wizard. Acceptance: labels exist; a PR gets a `size:*` label; `main` refuses a merge while `Check` is red; the PR template renders; a seeded ticket run with `/poteto-mode "#1"` reads the issue, checks blockers, raises falsifiability notes, runs the Feature playbook and reaches Opening a PR with `Closes #1` and a Verification section, never blocked by "skill cannot be invoked"; `/unslop` fires on its own when the agent drafts the PR body.

**M6 — Profiles (1 day).** §7.10–7.11. Acceptance, React Native: `factory918 apply --profile react-native` on the monorepo adds an Expo app that `vp check`, `pnpm typecheck` and `vp test run` cover; the fingerprint workflow runs on a PR touching `apps/mobile` and applies its label when a native dependency is added; the primary agent can launch a simulator and leave a screenshot in `.artifacts/`. Python: `factory918 apply --profile python` adds `python/<name>` with a passing `python.yml`; `print("x")` in a module fails `ast-grep scan` and `ruff check`; `os.system` fails `ruff check` with the banned-API message; `*.py` is formatted on commit in the monorepo; `uv audit` runs.

**M7 — `update` and `sync` (1 day).** §8.2. Acceptance: on a project at template v1, edit `AGENTS.md` locally, delete `docs/agents/feedback-loops.md`, bump the template to v2 (which changes `AGENTS.md` elsewhere and adds a file); `factory918 update` keeps the local edit, applies the template change, adds the new file, does not resurrect the deleted one, refreshes `docs/factory918/`, and produces a `.factory-merge` file only where lines actually collide. `factory918 sync` against a newer open-pstack tag re-applies all §5.4 patches with no manual edits and reports any patch that no longer applies.

**M8 — First real project and a retro (ongoing).** Apply to one real product monorepo. After two weeks: `/reflect`, read the ledger, promote the first recurring correction to a rule at the strongest rung that holds it; record it in `DECISIONS.md` under Provisional. That is when Factory918 stops being copied opinions and starts being Manuel's.

"""

# ---- §10 replace ----
key10 = k("10.")
sec[key10] = """## 10. Decisions

All previously open decisions are settled and recorded with reasons in `docs/knowledge/core/DECISIONS.md` (seventeen entries as of 2026-09-09). Deferred, not open: a Flutter profile (only if a project demands it); which external review bot to add, if any (rung 2 stays empty until PRs from more than one agent a day exist); Codex as a second harness (open-pstack's Codex path and `.agents/skills` being the Codex convention mean nothing in the template moves when it comes). New choices an agent has to make go under "Provisional" in `DECISIONS.md`.

"""

# ---- §11 additions ----
key11 = k("11.")
sec[key11] = sec[key11].rstrip() + """ Added in v2: `uv` (Python project, lockfile and interpreter manager); `ruff` (Python linter and formatter); `pyright` (Python type checker) and `ty` (Astral's, in beta); `pytest`; `uv audit` (dependency vulnerability scan); `ast-grep` (structural code search and lint across languages); Expo (the managed React Native toolchain) and EAS (Expo's cloud build service); Metro (React Native's bundler); the Expo fingerprint (a hash of the native runtime; if it changes, the app needs a store build, not an over-the-air update); Maestro (YAML-driven mobile e2e flows); `xcrun simctl` and `adb` (iOS simulator and Android device CLIs used for screenshots).
"""

out = pre + "".join(sec[key] for key in order)
(ROOT / "FACTORY-SPEC-v2.md").write_text(out)
print("v2 written:", len(out), "chars;", out.count("\n## "), "H2 sections")
